# Imagen base de Node
FROM node:20

# Crear carpeta dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Compilar la aplicación de React
RUN npm run build

# Servir la app con un servidor de producción
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "build"]
