# Imagen base de Node
FROM node:20

WORKDIR /app

# Copiar package.json del frontend
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código (sin ./frontend porque ya estás dentro de ese contexto)
COPY . .

# Compilar React
RUN npm run build

# Servir la app con serve
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "build"]
