version: "3.8"
services:
  backend:
    build: ./backend
    container_name: maquinova-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/maquinova_db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: maquinova-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: maquinova-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
