# Imagen base de Node
FROM node:20

# Crear carpeta dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto del backend
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["npm", "run", "dev"]
