name: CI/CD Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ Maquinova }}
        password: ${{ dckr_pat_qArVKLRN5NIwbqfXZ06Rn9al0ME }}

    - name: Construir imagen Docker
      run: docker build -t Maquinova/maquinova-app:latest .

    - name: Subir a Docker Hub
      run: docker push Maquinova/maquinova-app:latest

    - name: Instalar dependencias y ejecutar pruebas
      run: |
        npm install
        npm test -- --coverage
