name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Backend tests
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm install
          npm test -- --ci --coverage
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}


      # Frontend tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

  build:
    runs-on: ubuntu-latest
    needs: test   # 🔑 Solo corre si las pruebas pasan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/maquinova-backend ./backend
          docker push ${{ secrets.DOCKER_USER }}/maquinova-backend

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/maquinova-frontend ./frontend
          docker push ${{ secrets.DOCKER_USER }}/maquinova-frontend
